### ISSUE TITLE
No DML config menu in Foundry 0.8.9?

### ISSUE THREAD

**Issue by coffiarts** [hitcherland/foundryvtt-macro-to-del#2]
In Foundry VTT 0.8.9, the Dynamic Macro Links config entry seems to be gone. Is this a compatibility issue with the latest VTT version?

The docs here state: "[...] open up the settings tab and click 'Configure Settings' followed by 'Module Settings'. Here we can see the Dynamic Macro Links settings group."

In 0.8.9, I can't detect this group anymore, though DML Add-On is properly activated. 
Anyone else experiencing this?

**Comment by hitcherland** [comment]
This module hasn't yet been updated for the changes introduced from 0.7.x -> 0.8.x. The reason it won't show up in the settings is because it's entirely broken in 0.8.x.

I'm looking into bringing it up to date, but in the meanwhile you'll have to stick with single-use macros (which you can drag and drop onto a journal just fine).

**Comment by coffiarts** [comment]
Thanks, @hitcherland for the update! That's good to know. So I promise to be patient :)

**Comment by hitcherland** [comment]
I know this has been a huge delay, but I've now updated it for 9.249!
